#!/bin/bash

mode=mario
dir=/usr/share/sounds/fruitplayer
aplay -q $dir/1up.wav
count=0
banana=0
rand=$(( ( RANDOM % 25 )  + 15 ))
while true; do
IFS= read -r -s -n1 sound
if [ $sound = a ] ; then
	if [ $mode = mario ]; then
		aplay -q $dir/coin.wav &
	elif [ $mode = piano ];then
		aplay -q $dir/a.wav &
	fi
	count=0
	last=$sound
elif [ $sound = s ] ; then
	if [ $banana = $rand ];then
		aplay -q $dir/banana.wav &
		banana=0
		rand=$(( ( RANDOM % 25 )  + 15 ))
	else
		if [ $mode = mario ]; then
			aplay -q $dir/fireball.wav &
			(( banana++ ))
		elif [ $mode = piano ];then
			aplay -q $dir/b.wav &
		fi
	fi
	count=0
	last=$sound
elif [ $sound = d ] ; then
	if [ $mode = mario ]; then
		aplay -q $dir/jump.wav &
	elif [ $mode = piano ]; then
		aplay -q $dir/c.wav &
	fi
	count=0
	last=$sound
elif [ $sound = f ] ; then
	if [ $mode = mario ]; then
		aplay -q $dir/kick.wav &
	elif [ $mode = piano ]; then
		aplay -q $dir/d.wav &
	fi
	count=0
	last=$sound
elif [ $sound = g ] ; then
	if [ $mode = mario ]; then
		aplay -q $dir/mip.wav &
	elif [ $mode = piano ]; then
		aplay -q $dir/e.wav &
	fi
	count=0
	last=$sound
elif [ $sound = q ] ; then
	exit 0
elif [ $sound = w ] ; then
	aplay -q $dir/enter-stage.wav &
	sleep 1
	sudo shutdown -h now

elif [ "$sound" = ' ' ]; then
	if [ $last = g ] ;then
		if [ $mode = mario ]; then
			mode=piano
			echo "mode = $mode"
			aplay -q $dir/area_tag.wav &
		elif [ $mode = piano ]; then
			mode=mario
			echo "mode = $mode"
			aplay -q $dir/area_tag.wav &
		fi
	else
		ip=$(ip addr|grep "inet "|grep -v 127.0.0.1|awk '{print $2}'|awk -F/ '{print $1}'|grep -v ^$|head -n1)
		if [ $count = 0 ];then
			sudo espeak -ven+f3 -k5 -s100 "$ip" 2>/dev/null
			count=1
			sleep 1
		fi
	fi
fi
done
