#!/bin/bash

dir=/usr/share/sounds/fruitplayer
while true; do
read -s -n1 sound

if [ $sound = a ] ; then
	aplay -q $dir/coin.wav & 
elif [ $sound = s ] ; then
	aplay -q $dir/fireball.wav &
elif [ $sound = d ] ; then
	aplay -q $dir/jump.wav &
elif [ $sound = f ] ; then
	aplay -q $dir/kick.wav &
elif [ $sound = g ] ; then
	aplay -q $dir/mip.wav &
elif [ $sound = q ] ; then
	exit 0
fi
done
